INSERT INTO
    users (id, username, password)
VALUES
    (
        1,
        'test',
        '$2y$10$2ishFR3.Fl.pSLvMCw4Xv.g/NB6Q7fpT7y/YJzlKrhkGNUK5EvMgm'
    ),
    (
        2,
        'other',
        '$2y$10$2ishFR3.Fl.pSLvMCw4Xv.g/NB6Q7fpT7y/YJzlKrhkGNUK5EvMgm'
    );

INSERT INTO
    categories (id, user_id, name, sort_order)
VALUES
    (1, 1, '仕事', 1),
    (2, 1, 'プライベート', 2),
    (3, 1, '買い物', 3),
    (4, 1, '並び順テスト', 4),
    (5, 2, '他ユーザーのカテゴリ', 1);

INSERT INTO
    todos (
        id,
        user_id,
        title,
        status,
        details,
        due_date,
        due_date_undecided,
        auto_carry_over,
        is_daily,
        has_flag,
        category_id,
        parent_id,
        overdue_behavior,
        sort_order
    )
VALUES
    (
        1,
        1,
        'sortOrder 2 の仕事タスク',
        'INCOMPLETE',
        '並び順確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        4,
        NULL,
        0,
        2
    ),
    (
        2,
        1,
        'sortOrder 1 の仕事タスク',
        'INCOMPLETE',
        '並び順確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        4,
        NULL,
        0,
        1
    ),
    (
        3,
        1,
        '日付ありタスク',
        'INCOMPLETE',
        'existsDueDate確認用',
        '2026-05-20',
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        2,
        NULL,
        0,
        3
    ),
    (
        4,
        1,
        '期限未定タスク',
        'INCOMPLETE',
        'existsDueDate確認用',
        NULL,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        2,
        NULL,
        0,
        4
    ),
    (
        5,
        1,
        'カテゴリなしタスク',
        'INCOMPLETE',
        'categoryUnassigned確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        NULL,
        0,
        5
    ),
    (
        6,
        1,
        '親タスク',
        'INCOMPLETE',
        'parentId確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        1,
        NULL,
        0,
        6
    ),
    (
        7,
        1,
        '子タスクA',
        'INCOMPLETE',
        'parentId確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        6,
        0,
        1
    ),
    (
        8,
        1,
        '子タスクB',
        'DONE',
        'parentId確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        NULL,
        6,
        0,
        2
    ),
    (
        9,
        2,
        '他ユーザーのタスク',
        'INCOMPLETE',
        'user_id分離確認用',
        NULL,
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        5,
        NULL,
        0,
        1
    );
