spring.application.name=AllTaskTodo
# H2データベースへの接続設定（メモリモード）
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# # H2コンソール（ブラウザで中身を見るための画面）を有効にする
# spring.h2.console.enabled=true
# # ブラウザからアクセスする際のパス（http://localhost:8080/h2-console）
# spring.h2.console.path=/h2-console
# # 起動時に src/main/resources/schema.sql を実行する設定
# spring.sql.init.mode=always
# mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler

# MySQLへの接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/alltask_db?createDatabaseIfNotExist=true&characterEncoding=utf-8&serverTimezone=Asia/Tokyo
# spring.datasource.url=jdbc:mysql://db:3306/alltask_db?createDatabaseIfNotExist=true&characterEncoding=utf-8&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=0002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 初期化設定（初回起動時にテーブルを作成する場合）
spring.sql.init.mode=always
mybatis.configuration.map-underscore-to-camel-case=true