---------------------------------------------------------------------------
-- Production initial setup SQL for PostgreSQL
-- Run this only for the first setup of an empty production database.
-- This file intentionally does not contain DROP TABLE statements.
---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(50) NOT NULL,
    sort_order INTEGER NULL,
    CONSTRAINT fk_categories_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS todos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(100),
    status VARCHAR(20),
    details VARCHAR(500),
    due_date DATE,
    due_date_undecided BOOLEAN DEFAULT FALSE,
    auto_carry_over BOOLEAN DEFAULT FALSE,
    is_daily BOOLEAN DEFAULT FALSE,
    daily_reset_date DATE,
    has_flag BOOLEAN DEFAULT FALSE,
    category_id INTEGER,
    parent_id INTEGER,
    overdue_behavior INTEGER DEFAULT 0,
    sort_order INTEGER NULL,
    CONSTRAINT fk_todos_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_todos_category
        FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_todos_parent
        FOREIGN KEY (parent_id) REFERENCES todos (id) ON DELETE CASCADE
);
